// Code generated by the FlatBuffers compiler. DO NOT EDIT.
//
// Vendored from github.com/teslamotors/fleet-telemetry/messages/tesla
// to avoid pulling fleet-telemetry's heavy transitive dependencies
// (Kafka, GCP Pub/Sub, ZeroMQ, etc.).

package tesla

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlatbuffersEnvelope struct {
	_tab flatbuffers.Table
}

func GetRootAsFlatbuffersEnvelope(buf []byte, offset flatbuffers.UOffsetT) *FlatbuffersEnvelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlatbuffersEnvelope{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FlatbuffersEnvelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlatbuffersEnvelope) Table() flatbuffers.Table {
	return rcv._tab
}

// txid: unique transaction id of this message
func (rcv *FlatbuffersEnvelope) Txid(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FlatbuffersEnvelope) TxidLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FlatbuffersEnvelope) TxidBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// topic: used for routing messages to backend queues
func (rcv *FlatbuffersEnvelope) Topic(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FlatbuffersEnvelope) TopicLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FlatbuffersEnvelope) TopicBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FlatbuffersEnvelope) MessageType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FlatbuffersEnvelope) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *FlatbuffersEnvelope) MessageIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FlatbuffersEnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func FlatbuffersEnvelopeAddTxid(builder *flatbuffers.Builder, txid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(txid), 0)
}
func FlatbuffersEnvelopeAddTopic(builder *flatbuffers.Builder, topic flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(topic), 0)
}
func FlatbuffersEnvelopeAddMessageType(builder *flatbuffers.Builder, messageType byte) {
	builder.PrependByteSlot(2, messageType, 0)
}
func FlatbuffersEnvelopeAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(message), 0)
}
func FlatbuffersEnvelopeAddMessageId(builder *flatbuffers.Builder, messageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(messageId), 0)
}
func FlatbuffersEnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
