// Code generated by the FlatBuffers compiler. DO NOT EDIT.
//
// Vendored from github.com/teslamotors/fleet-telemetry/messages/tesla
// to avoid pulling fleet-telemetry's heavy transitive dependencies
// (Kafka, GCP Pub/Sub, ZeroMQ, etc.).

package tesla

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FlatbuffersStream struct {
	_tab flatbuffers.Table
}

func GetRootAsFlatbuffersStream(buf []byte, offset flatbuffers.UOffsetT) *FlatbuffersStream {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FlatbuffersStream{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FlatbuffersStream) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FlatbuffersStream) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FlatbuffersStream) CreatedAt() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

// sender_id: device identity coming from the certificate — DEPRECATED: use device_type + device_id
func (rcv *FlatbuffersStream) SenderIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FlatbuffersStream) PayloadBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// device_type: device identity coming from the certificate derived of Issuer CN
func (rcv *FlatbuffersStream) DeviceTypeBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// device_id: device identity coming from the certificate derived of Subject CN
func (rcv *FlatbuffersStream) DeviceIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// delivered_at_epoch_ms: timestamp (in ms) at which the message reached the backend
func (rcv *FlatbuffersStream) DeliveredAtEpochMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func FlatbuffersStreamStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func FlatbuffersStreamAddCreatedAt(builder *flatbuffers.Builder, createdAt uint32) {
	builder.PrependUint32Slot(0, createdAt, 0)
}
func FlatbuffersStreamAddSenderId(builder *flatbuffers.Builder, senderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(senderId), 0)
}
func FlatbuffersStreamAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(payload), 0)
}
func FlatbuffersStreamAddDeviceType(builder *flatbuffers.Builder, deviceType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(deviceType), 0)
}
func FlatbuffersStreamAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(deviceId), 0)
}
func FlatbuffersStreamAddDeliveredAtEpochMs(builder *flatbuffers.Builder, deliveredAtEpochMs uint64) {
	builder.PrependUint64Slot(5, deliveredAtEpochMs, 0)
}
func FlatbuffersStreamEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
